navigation:
- text: Home
  url: /
- text: API Docs
  url: /Open-Notify-API
  name: apidoc
- text: Source Code
  url: https://github.com/open-notify
- text: About
  url: /about.html

apis:
 - text: ISS Current Location
   url: /Open-Notify-API/ISS-Location-Now
   name: issnow
 - text: ISS Pass Times
   url: /Open-Notify-API/ISS-Pass-Times
   name: isspass
