navigation:
- text: Home
  url: /
- text: API Docs
  url: /Open-Notify-API
  layout: page
- text: Source Code
  url: https://github.com/open-notify
- text: About
  url: /about.html

apis:
 - text: ISS Location
   url: /Open-Notify-API/ISS-Location-Now
