---
dependencies:
  - role: nginx

    nginx_http_params:
        - sendfile on
        - tcp_nopush on
        - tcp_nodelay on
        - gzip on
        - server_tokens off
        - index index.html
        - log_format apilog '$msec | $remote_addr $status $request_time $upstream_response_time $upstream_cache_status $body_bytes_sent | "$scheme $request" "$http_user_agent"'

    nginx_events_params:
        - worker_connections 16348
        - use epoll
        - multi_accept on

    nginx_sites:

      default:
        - listen 80 default_server
        - server_name ""
        - return 444
      defaulthttps:
        - listen 443 ssl default_server
        - server_name ""
        - ssl_certificate /etc/letsencrypt/live/api.open-notify.org/fullchain.pem
        - ssl_certificate_key /etc/letsencrypt/live/api.open-notify.org/privkey.pem
        - return 444

      # Enable monitoring
      datadogmonitor:
        - listen 9841
        - server_name localhost
        - location / {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
          }

      # The API
      api:
        - listen 80
        - server_name *.open-notify.org
        - access_log /var/log/nginx/iss.access.log apilog
        - root /opt/web/static/
        - add_header 'Access-Control-Allow-Origin' '*'
        - add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS'
        - add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Accept,Origin'
        - location @proxy {
            error_page 502 = @fallback;
            uwsgi_pass unix:///tmp/uwsgi.sock;
            include uwsgi_params;
          }
        - location / {
            try_files $uri $uri/ @proxy;
          }
        - location @fallback {
            default_type application/json;
            return 502 '{"message":"Temporarily unavailable"}';
          }

      apihttps:
        - listen 443 ssl
        - server_name *.open-notify.org
        - access_log /var/log/nginx/iss.access.log apilog
        - root /opt/web/static/
        - ssl_certificate /etc/letsencrypt/live/api.open-notify.org/fullchain.pem
        - ssl_certificate_key /etc/letsencrypt/live/api.open-notify.org/privkey.pem
        - ssl_protocols TLSv1.1 TLSv1.2
        - ssl_prefer_server_ciphers on
        - ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH'
        - ssl_dhparam /etc/ssl/private/dhparams.pem
        - ssl_session_cache shared:SSL:10m
        - ssl_session_timeout 10m
        #- add_header Strict-Transport-Security "max-age=31536000; includeSubdomains"
        #- add_header Content-Security-Policy "script-src 'self'"
        #- add_header X-Frame-Options "DENY"
        #- add_header X-Xss-Protection "1; mode=block"
        #- add_header X-Content-Type-Options "nosniff"
        - add_header 'Access-Control-Allow-Origin' '*'
        - add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS'
        - add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Accept,Origin'
        - location @proxy {
            error_page 502 = @fallback;
            uwsgi_pass unix:///tmp/uwsgi.sock;
            include uwsgi_params;
          }
        - location / {
            try_files $uri $uri/ @proxy;
          }
        - location @fallback {
            default_type application/json;
            return 502 '{"message":"Temporarily unavailable"}';
          }
