---

- name: Create Static Site Directory
  file:
    path: /opt/web/static/
    state: directory
    owner: www-data
    group: www-data
    mode: 0555
    recurse: yes

- name: Dummy index.html file
  copy:
    content: "open-notify.org"
    dest: /opt/web/static/index.html
    owner: www-data
    group: www-data
    mode: 0444
    force: no
