---
- name: Update Apt
  apt: update_cache=yes


- name: Install Python Runtime
  apt: name={{ item }} state=present
  with_items:
    - python3.5
    - python3-virtualenv


- name: Install UWSGI
  apt: name={{ item }} state=present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3


- name: Install Redis
  apt: name={{ item }} state=present
  with_items:
    - redis-server


- name: Create a System Service For API
  template:
    src: open-notify-api.service.j2
    dest: /etc/systemd/system/open-notify-api.service


- name: Register open-notify-api.service
  systemd: name=open-notify-api daemon_reload=yes
