---
- name: Update Apt
  apt: update_cache=yes

- name: Install Basic Packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - curl
    - ntp
    - build-essential

- name: Make 'sudo' Group
  group:
   name: sudo
   state: present

- name: Allow Password-less 'sudo'
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: Create User 'deploy'
  user:
    name: deploy
    state: present
    groups: sudo
    append: yes
    createhome: yes
    shell: /bin/bash

- name: Set 'deploy' User Authorized Key From Current User
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('pipe', 'ssh-add -L') }}"

- name: User 'deploy' set bashrc alias 'll'
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    regexp: "^#alias ll="
    line: "alias ll='ls -l'"

- name: User 'deploy' set bashrc color term
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    regexp: "^#force_color_prompt="
    line: "force_color_prompt=yes"

- name: User 'deploy' Set '.vimrc'
  template:
    src: vimrc.j2
    dest: /home/deploy/.vimrc
    owner: deploy
    group: deploy
