---
- name: Update Apt
  apt: update_cache=yes

- name: Install Basic Packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - curl
    - ntp
    - build-essential

- name: Make 'sudo' Group
  group:
   name: sudo
   state: present

- name: Allow Password-less 'sudo'
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: Create User 'deploy'
  user:
    name: deploy
    state: present
    groups: sudo
    append: yes
    createhome: yes
    shell: /bin/bash

- name: Set 'deploy' User Authorized Key From Current User
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('pipe', 'ssh-add -L') }}"

- name: User 'deploy' Create Local 'bin' Directory
  file:
    path: /home/deploy/bin/
    state: directory
    owner: deploy
    group: deploy
    mode: 0755

- name: User 'deploy' set bashrc color term
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    backrefs: yes
    regexp: "^#force_color_prompt="
    line: "force_color_prompt=yes"
    backup: yes

- name: User 'deploy' set bashrc alias 'll'
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    backrefs: yes
    regexp: "^#alias ll="
    line: "alias ll='ls -l'"
    backup: yes

- name: User 'deploy' Add bin To PATH
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    regexp: '^export PATH="\$PATH:\$HOME\/bin"'
    line: 'export PATH="$PATH:$HOME/bin"'
    backup: yes

- name: User 'deploy' Color Prompt
  lineinfile:
    dest: /home/deploy/.bashrc
    state: present
    backrefs: yes
    regexp: 'PS1=''\${debian_chroot:\+\(\$debian_chroot\)}\\\[\\033\['
    line: '    PS1=''${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h (PRODUCTION)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '''
    backup: yes

- name: User 'deploy' Set '.vimrc'
  template:
    src: vimrc.j2
    dest: /home/deploy/.vimrc
    owner: deploy
    group: deploy

- name: User 'deploy' Copy 'bin' Templates
  template:
    src: start-api.j2
    dest: /home/deploy/bin/start-api
    owner: deploy
    group: deploy
    mode: 0554

- name: User 'deploy' Copy 'bin' Templates
  template:
    src: stop-api.j2
    dest: /home/deploy/bin/stop-api
    owner: deploy
    group: deploy
    mode: 0554

- name: User 'deploy' Copy 'bin' Templates
  template:
    src: tail-nginx.j2
    dest: /home/deploy/bin/tail-nginx
    owner: deploy
    group: deploy
    mode: 0554

- name: User 'deploy' Copy 'bin' Templates
  template:
    src: upgrade.j2
    dest: /home/deploy/bin/upgrade
    owner: deploy
    group: deploy
    mode: 0554

- name: Add A Fun MOTD
  template:
    src: motd.j2
    dest: /etc/motd
